//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public long SongID { get; set; }
        public Nullable<long> ArtistID { get; set; }
        public string Title { get; set; }
        public Nullable<int> YearReleased { get; set; }
        public bool Enable { get; set; }
    
        public virtual Artists Artists { get; set; }
    }
}
